CREATE ROLE IF NOT EXISTS emberlog_app LOGIN PASSWORD 'Emb3rL0g@pp2025';
CREATE SCHEMA IF NOT EXISTS emberlog AUTHORIZATION emberlog_app;
ALTER ROLE emberlog_app SET search_path TO emberlog,public;
GRANT USAGE ON SCHEMA emberlog TO emberlog_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA emberlog TO emberlog_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA emberlog
  GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO emberlog_app;
